Notifications support
sysrepo/sysrepo-python pull request #16
Opened 2021-09-15 20:55 UTC by nicolasmorini

Hi @rjarry!

Please consider this pull request that adds support for notifications.

This pull-request depends directly on the following pull-request on libyang-python: https://github.com/CESNET/libyang-python/pull/26

This is the follow up of the discussion here: sysrepo/sysrepo-python#10 (apologies for the delay on making this contribution).

Please note that I had to do several changes in the CI workflow to make it build and pass, since the release of libyang2, new versions of pylint and ubuntu-latest resolving to ubuntu-20.04 broke the process.

2021-09-15 20:57 UTC, nicolasmorini commented on setup.py
> +        "libyang>1.6.1,<2",
This probably needs to be adapted accordingly once the corresponding libyang-python release is available. For now I just wanted to signal that it requires a version that does not exist yet.

2021-09-16 07:59 UTC, rjarry requested changes
Hi @nicolasmorini,

overall this looks good. Could you address the few remarks I have made?

Thanks.

2021-09-16 07:59 UTC, rjarry commented on .github/workflows/ci.yml
> +          #  toxenv: py3-devel
I guess you can remove the master and devel branches. I'll add them again when working on libyang 2 support.

2021-09-16 07:59 UTC, rjarry commented on cffi/build.py
> +with open(os.path.join(HERE, "cdefs.h"), encoding="utf-8") as f:
Did you have a problem with the default encoding? These files only contain ASCII characters as far as I know.

2021-09-16 07:59 UTC, rjarry commented on tox.ini
> +envlist = format,lint,py{35,36,37,38,py3},py3-{master,devel,libyang1},coverage
You can remove the master and devel branches.

2021-09-16 07:59 UTC, rjarry commented on tox.ini
>  	devel: SYSREPO_BRANCH = devel
Same here about the branches.

2021-09-16 07:59 UTC, rjarry commented on setup.py
> +        "libyang>1.6.1,<2",
Ok, I'll integrate your work on https://github.com/CESNET/libyang-python/pull/26 first and make an official release. Then you'll be able to update your code with the new version.

2021-09-16 07:59 UTC, rjarry commented on sysrepo/subscription.py
> +
nitpick: could you add a separator line? I am quite anal about these :)

```python
# ------------------------------------------------------------------------------
```

2021-09-16 07:59 UTC, rjarry commented on sysrepo/subscription.py
> +    callback(xpath, notif_type, notif_dict, timestamp, private_data)
You should wrap all this in a try/except block catching all exceptions. See all C callback handlers for reference.

2021-09-16 07:59 UTC, rjarry commented on sysrepo/session.py
> +            {'some-notification': {'param1': 42, 'param2': 'foobar'}}
I feel like the notification dict should look like the one in RPCs and actions. See commit https://github.com/sysrepo/sysrepo-python/commit/3073a2cfdb8662e65645a63ce628ad3ad4706b4c for the reasoning around this design decision. Basically, the xpath allows identifying the data-tree position of the rpc/action and the dict contains only the input/output nodes.

https://github.com/sysrepo/sysrepo-python/blob/master/sysrepo/session.py#L335-L365

https://github.com/sysrepo/sysrepo-python/blob/master/sysrepo/subscription.py#L465-L469

2021-09-16 07:59 UTC, rjarry commented on sysrepo/session.py
> +        )
Following my previous comment, the notification dict should only contain the inner nodes and the xpath should be used to construct the complete data tree. See commit https://github.com/sysrepo/sysrepo-python/commit/1a070313ee4e9dec5b30c5f4b0269a2cf8dabaf0.

https://github.com/sysrepo/sysrepo-python/blob/master/sysrepo/session.py#L981-L984

2021-09-16 07:59 UTC, rjarry commented on tests/test_subs_notification.py
> +        }
After changing the notification dict structure, could you add a test with a notification [nested in a data element](https://datatracker.ietf.org/doc/html/rfc7950#section-7.16.3)? You can have a look at commit https://github.com/sysrepo/sysrepo-python/commit/1a070313ee4e9dec5b30c5f4b0269a2cf8dabaf0 for inspiration.

2021-09-16 08:26 UTC, nicolasmorini commented on cffi/build.py
> +with open(os.path.join(HERE, "cdefs.h"), encoding="utf-8") as f:
I added it to make pylint happy (it is a new warning added recently):

- unspecified-encoding (W1514) (https://pylint.pycqa.org/en/latest/technical_reference/features.html)
- https://pylint.pycqa.org/en/latest/whatsnew/2.10.html

Alternatively, I can disable that specific warning, either inline or altogether in pylintrc. What are your thoughts on this?

2021-09-16 08:28 UTC, nicolasmorini commented
@rjarry, I'll address the remaining comments about dict usage and exception handling later today

2021-09-16 11:26 UTC, rjarry commented on cffi/build.py
> +with open(os.path.join(HERE, "cdefs.h"), encoding="utf-8") as f:
Ok that looks good then, leave it like this :+1:

2021-09-16 21:57 UTC, rjarry commented
[Libyang 1.7.0 is out](https://pypi.org/project/libyang/). You can update `setup.py` accordingly :)

2021-09-16 21:58 UTC, rjarry commented on setup.py
> +        "libyang>1.6.1,<2",
[Libyang 1.7.0](https://pypi.org/project/libyang/) is out :)

2021-09-17 12:03 UTC, rjarry commented
@nicolasmorini could you squash all your fixups please? You can ignore the codecov report. It is impossible to have coverage on C callbacks...

2021-09-17 15:07 UTC, merged

2021-09-17 16:03 UTC, rjarry commented
Included in [0.5.0](https://pypi.org/project/sysrepo/), thanks @nicolasmorini :+1:

2021-09-20 13:48 UTC, nicolasmorini commented
Thanks a lot for the support and the prompt responses @rjarry! I will start using these new releases this week!