libyang2: Make sysrepo-python works with libyang2
sysrepo/sysrepo-python pull request #28
Opened 2022-03-02 09:14 UTC by jeanseb6wind

Since libyang2 migration, sysrepo-python is no more compatible with the
master branch of sysrepo. It's because sysrepo migrate to libyang2.

This patch adds the support of the new version of sysrepo.

2022-03-02 10:03 UTC, jeanseb6wind commented
I have a problem with the last `sysrepo-python` commit on `master`.
Indeed, this commit uses the functions 

```
uint32_t sr_session_get_event_nc_id(sr_session_ctx_t *);
const char *sr_session_get_event_user(sr_session_ctx_t *);
```

Theses functions are not here anymore and now if you want to get theses data you have to use the new function 

```
int sr_session_get_orig_data(sr_session_ctx_t *session, uint32_t idx, uint32_t *size, const void **data)
```

You can compare this test to see the differences:

v1: https://github.com/sysrepo/sysrepo/blob/libyang1/tests/test_operational.c#L1082
v2: https://github.com/sysrepo/sysrepo/blob/master/tests/test_operational.c#L1001

The problem is that the `nc_id` and `user` should manually be set with `sr_session_push_orig_data`.

It's similar in v1, the `nc_id` should be set manually with `sr_session_set_nc_id(st->sess, 64);`. So I don't understand how works the last commit of `sysrepo-python` on `master`.

2022-03-03 10:57 UTC, jeanseb6wind commented
Errors comes (in part) form the uses of bad version of libyang and sysrepo.

2022-03-15 19:11 UTC, tarkesh commented
> Errors comes (in part) form the uses of bad version of libyang and sysrepo.

looks like we need the libyang-python 2.0 version too - https://github.com/pepa-cz/libyang-python/tree/libyang2_support which is still in a branch. Once that is installed, the check passes.
The syrepo cffi bindings are still on 1.x version somehow - i'm still looking for where they are defined. 
Did you have any luck in building it?

2022-04-29 12:26 UTC, rjarry requested changes
Hey there. There are a few changes that I would like. Thanks for working on this. :+1:

2022-04-29 12:26 UTC, rjarry commented on Makefile
> +	tox -e py37
This should not be pinned to a specific version of python.

2022-04-29 12:26 UTC, rjarry commented on sysrepo/session.py
> +        It only works with netopeer2.
I am not sure about this comment. Why would it only work with netopeer2? It works as soon as someone reports this via `sr_session_push_orig_data`.

2022-04-29 12:26 UTC, rjarry commented on sysrepo/session.py
> +        It only works with netopeer2.
Same remark than above. Please remove this line.

2022-04-29 12:26 UTC, rjarry commented on sysrepo/session.py
> +            raise SysrepoUnsupportedError("can only report netconf id for netopeer2")
I don't understand this. Why would you restrict this to a specific originator?

2022-04-29 12:26 UTC, rjarry commented on sysrepo/session.py
> +        dnode.free = lambda: lib.sr_release_data(sr_data_p[0])
This is too much of a hack. Please create a subclass of `libyang.DNode` if you need to override something.

2022-04-29 12:26 UTC, rjarry commented on sysrepo/session.py
> +        return libyang.DNode.new(self.get_ly_ctx(), sr_data_p[0].tree)
Use the same class with overridden `free()`?

2022-04-29 12:26 UTC, rjarry commented on tests/test_subs_module_change.py
> +            # ]
Remove this comment?

2022-05-09 16:54 UTC, jeanseb6wind commented on sysrepo/session.py
> +        dnode.free = lambda: lib.sr_release_data(sr_data_p[0])
Hello @rjarry The problem is that the object is generate inside libyang. So I could update libyang by adding a parameter allowing to customize the free method but I'm not sure it's a good way to update libyang for that. What do you think about it ?

2022-05-23 19:27 UTC, rjarry approved these changes

2022-05-23 20:24 UTC, rjarry commented
I merged this manually. Thanks a lot for your work!

2022-05-23 20:24 UTC, closed without merging