change: add deleted value to ChangeDeleted
sysrepo/sysrepo-python pull request #32
Opened 2022-07-15 13:41 UTC by avazquezrd

We can get deleted value from node argument passed in `Change.parse()`, so we can add this additional attribute to `ChangeDeleted`.

2022-07-27 16:16 UTC, Krisscut commented
I agree that it would be nice to have this feature merged in the trunk and the official deliveries.

Thanks for providing that pull request as a reference in the meantime !

2022-07-28 07:43 UTC, AeroFlorian commented
Code is working and that would be great if it could be merged!

2022-07-28 07:43 UTC, AeroFlorian approved these changes

2022-07-28 08:23 UTC, rjarry commented
Hi,

Could you put a description in the commit message? See [this link](https://www.kernel.org/doc/html/latest/process/submitting-patches.html#describe-your-changes) for guidelines.

Also, I wonder what happens when a presence container or list element is deleted. Could you add unit tests to ensure every use case works? Container, ContainerPresence, List, Leaf, etc.

Thanks!

2022-07-28 08:39 UTC, rjarry requested changes
Hi,

Could you put a description in the commit message? See [this link](https://www.kernel.org/doc/html/latest/process/submitting-patches.html#describe-your-changes) for guidelines.


I fear this would brings a significant performance hit when there are a lot of changes. When deleting a container, the value is a dict containing the recursive deleted data. I would really prefer if the `ChangeDeleted` for `List` and `Container` nodes would have `None` as value. 

Also, could you add unit tests to ensure every use case works?

Thanks!

2022-07-28 11:55 UTC, avazquezrd commented
> Hi,
> 
> Could you put a description in the commit message? See [this link](https://www.kernel.org/doc/html/latest/process/submitting-patches.html#describe-your-changes) for guidelines.
> 
> I fear this would brings a significant performance hit when there are a lot of changes. When deleting a container, the value is a dict containing the recursive deleted data. I would really prefer if the `ChangeDeleted` for `List` and `Container` nodes would have `None` as value.
> 
> Also, could you add unit tests to ensure every use case works?
> 
> Thanks!

I have added the change for `Container` nodes (includes `List`). For tests, I have seen that they are already included for `Container` (line 108 in `tests_subs_module_change`), which would be the special case we have. Are there any other use cases you want to include?

2022-07-28 19:36 UTC, rjarry requested changes
Hi,

could you wrap your commit description at 72 characters? Your favorite text editor should do that automatically.

Thanks!

2022-07-28 19:36 UTC, rjarry commented on sysrepo/change.py
> +                else None,
How about the other node types?

I think the best you can do is to only get the value if the node is a leaf or leaf-list:

```python
    if isinstance(node, (libyang.DLeaf, libyang.DLeafList)):
        value = node.value()
    else:
        value = None
    return ChangeDeleted(node.path(), value)
```

2022-08-17 08:46 UTC, rjarry approved these changes
Sorry for the delay, this looks good. Thanks!

2022-08-17 08:46 UTC, merged

2022-08-31 07:28 UTC, Krisscut commented
For our usecase, we need this change, but the changes that are important for us are actually in a DContainer !
So the check for a DLeaf or DLeafList prevent us from having the node's value.

Would it be possible to have this behavior configurable, so that the user can judge is he can take the small performance hit ?
To have consistency in our code we would like to avoid having to implement some kind of caching mechanism when the information could come from the notification directly.

For instance, can we add a parameter to have a "short" or "full" description when we receive the list of changes ?

2022-08-31 07:41 UTC, avazquezrd commented
> For our usecase, we need this change, but the changes that are important for us are actually in a DContainer ! So the check for a DLeaf or DLeafList prevent us from having the node's value.
> 
> Would it be possible to have this behavior configurable, so that the user can judge is he can take the small performance hit ? To have consistency in our code we would like to avoid having to implement some kind of caching mechanism when the information could come from the notification directly.
> 
> For instance, can we add a parameter to have a "short" or "full" description when we receive the list of changes ?

I also think it would be useful to have the ability to be able to retrieve the value in lists and containers. It is true that, one way or another, when retrieving the changes of the values inside the container we would end up having this information, but it makes it a bit complicated.

Also, in the case of `ChangeCreated` or `ChangeModified`, we are getting the value of lists and containers. For consistency, wouldn't it be better to do the same for `ChangeDeleted`? As @Krisscut comments, we could make this option configurable if performance is a major issue.

2022-08-31 08:05 UTC, rjarry commented
If that is needed, we could add a new optional `full` parameter to `Session.get_changes` (default to `False`). Do you want to send a new PR?

2022-08-31 08:22 UTC, avazquezrd commented
In case we add a `full` parameter to `Session.get_changes`, how would the user be able to configure this parameter for changes passed in module change callback? 

I see that `Session.get_changes` is called in `module_change_callback` from `sysrepo.subscription` module, which is mapped to `srpy_module_change_cb` C function with same arguments, and this one is called in `Session.subscribe_module_change`, where I think it would be a good idea to have the configurable parameter. However, we cannot modify the number of arguments in `srpy_module_change_cb`, as this is used by C library, right? Correct me if I am wrong, please.

2022-08-31 08:50 UTC, rjarry commented
Perhaps something along these lines (not tested):

```diff
diff --git a/sysrepo/change.py b/sysrepo/change.py
index acc06c78d768..a6beea37e530 100644
--- a/sysrepo/change.py
+++ b/sysrepo/change.py
@@ -31,6 +31,7 @@ def parse(
         prev_list: str,
         prev_dflt: bool,
         include_implicit_defaults: bool = True,
+        include_deleted_values: bool = False,
     ) -> "Change":
         """
         Parse an operation code and values from libsysrepo.so and return a Change
@@ -64,6 +65,8 @@ def parse(
             Previous value default flag, depends on the operation.
         :arg include_implicit_defaults:
             Include implicit default values into the data dictionaries.
+        :arg include_deleted_values:
+            Include deleted nodes values.
         """
         if operation == lib.SR_OP_CREATED:
             if not node.should_print(
@@ -83,8 +86,8 @@ def parse(
                 prev_dflt=prev_dflt,
             )
         if operation == lib.SR_OP_DELETED:
-            if isinstance(node, (libyang.DLeaf, libyang.DLeafList)):
-                value = node.value()
+            if include_deleted_values:
+                value = _node_value(node, include_implicit_defaults)
             else:
                 value = None
             return ChangeDeleted(node.path(), value)
diff --git a/sysrepo/session.py b/sysrepo/session.py
index 06d2377a4488..1f1ba6f2514d 100755
--- a/sysrepo/session.py
+++ b/sysrepo/session.py
@@ -293,6 +293,7 @@ def subscribe_module_change(
         private_data: Any = None,
         asyncio_register: bool = False,
         include_implicit_defaults: bool = True,
+        include_deleted_values: bool = False,
         extra_info: bool = False,
     ) -> None:
         """
@@ -329,6 +330,8 @@ def subscribe_module_change(
             monitored read file descriptors. Implies `no_thread=True`.
         :arg include_implicit_defaults:
             Include implicit default nodes in changes.
+        :arg include_deleted_values:
+            Include deleted node values in changes.
         :arg extra_info:
             When True, the given callback is called with extra keyword arguments
             containing extra information of the sysrepo session that gave origin to the
@@ -343,6 +346,7 @@ def subscribe_module_change(
             private_data,
             asyncio_register=asyncio_register,
             include_implicit_defaults=include_implicit_defaults,
+            include_deleted_values=include_deleted_values,
             extra_info=extra_info,
         )
         sub_p = ffi.new("sr_subscription_ctx_t **")
@@ -732,7 +736,10 @@ def subscribe_notification(
 
     # begin: changes
     def get_changes(
-        self, xpath: str, include_implicit_defaults: bool = True
+        self,
+        xpath: str,
+        include_implicit_defaults: bool = True,
+        include_deleted_values: bool = False,
     ) -> Iterator[Change]:
         """
         Return an iterator that will yield all pending changes in the current session.
@@ -743,6 +750,8 @@ def get_changes(
             appended to the XPath.
         :arg include_implicit_defaults:
             Include implicit default nodes.
+        :arg include_deleted_values:
+            Include deleted node values into the returned Change objects.
 
         :returns:
             An iterator that will yield `sysrepo.Change` objects.
@@ -778,6 +787,7 @@ def get_changes(
                             prev_list=c2str(prev_list_p[0]),
                             prev_dflt=bool(prev_dflt_p[0]),
                             include_implicit_defaults=include_implicit_defaults,
+                            include_deleted_values=include_deleted_values,
                         )
                 except Change.Skip:
                     pass
diff --git a/sysrepo/subscription.py b/sysrepo/subscription.py
index e7b2ffae3b34..93c317da9c2f 100755
--- a/sysrepo/subscription.py
+++ b/sysrepo/subscription.py
@@ -33,6 +33,7 @@ def __init__(
         asyncio_register: bool = False,
         strict: bool = False,
         include_implicit_defaults: bool = True,
+        include_deleted_values: bool = False,
         extra_info: bool = False,
     ):
         """
@@ -50,6 +51,9 @@ def __init__(
         :arg include_implicit_defaults:
             If True, include implicit default nodes into Change objects passed to module
             change callbacks and into input parameters passed to RPC/action callbacks.
+        :arg include_deleted_values:
+            If True, include the complete deleted node values into Change objects passed
+            to module change callbacks.
         :arg extra_info:
             When True, the given callback is called with extra keyword arguments
             containing extra information of the sysrepo session that gave origin to the
@@ -64,6 +68,7 @@ def __init__(
         self.asyncio_register = asyncio_register
         self.strict = strict
         self.include_implicit_defaults = include_implicit_defaults
+        self.include_deleted_values = include_deleted_values
         self.extra_info = extra_info
         if asyncio_register:
             self.loop = asyncio.get_event_loop()
@@ -242,6 +247,7 @@ def module_change_callback(session, sub_id, module, xpath, event, req_id, priv):
                     session.get_changes(
                         root_xpath + "//.",
                         include_implicit_defaults=subscription.include_implicit_defaults,
+                        include_deleted_values=subscription.include_deleted_values,
                     )
                 )
                 task = subscription.loop.create_task(
```

2022-08-31 09:19 UTC, avazquezrd commented
Thanks for the suggestion! I will take a look at it and test it. When it is ready I will open a new PR.

2022-08-31 12:01 UTC, Krisscut commented
Thanks guys for the fast feedback and proposals !

The new include_deleted_values param in the subscribe_module_change would be a good solution indeed to provide the choice to the user.

2022-09-01 11:56 UTC, avazquezrd commented
I have added a minor fix to changes suggested by @rjarry, some tests and it seems to be working fine (see #37).