Optionally retrieve values in ChangeDeleted
sysrepo/sysrepo-python pull request #37
Opened 2022-09-01 11:46 UTC by avazquezrd

From #32. Now values are retrieved in `ChangeDeleted` for `List` and `Container` node types and getting deleted values is optional, configurable by user application with `include_deleted_values` when subscription is created (by default, `False`, it does not get deleted values).

Added some tests for this functionality.

2022-09-01 12:00 UTC, avazquezrd commented
`make lint` is working fine and without errors locally, not sure what the problem could be for the error I see in GitHub CI.

2022-09-02 07:45 UTC, rjarry commented
> `make lint` is working fine and without errors locally, not sure what the problem could be for the error I see in GitHub CI.

There was a change either in `astroid-2.12` or `pylint-2.15` that broke introspection of cffi modules. I'll freeze `pylint` to `2.14.*` until we have a fix.

2022-09-02 07:50 UTC, rjarry commented
Can you rebase your branch on the latest `master` and `push --force` to trigger the CI again?

2022-09-02 09:11 UTC, rjarry requested changes
Could you change the commit title to use a prefix?

```
changes: optionally include values in ChangeDeleted

Add a new include_deleted_values argument to `subscribe_module_change`.
Allows the user to choose whether to retrieve the values of nodes
deleted in ChangeDeleted when generating the subscription (by default,
False). This now also includes List and Container nodes.
```

Also, please include `--signoff` when creating the commit.

The code looks fine. Thanks!

2022-09-13 14:06 UTC, rjarry approved these changes

2022-09-13 14:06 UTC, merged

2022-09-14 20:03 UTC, Krisscut commented
Thank you to both of you for your work on this matter !
Is it possible to apply a new tag related to this change please ?

2022-09-16 07:32 UTC, rjarry commented
@Krisscut done

https://github.com/sysrepo/sysrepo-python/actions/runs/3066123792
https://pypi.org/project/sysrepo/1.3.0/