Draft: callback: return session when sync change callback is used
sysrepo/sysrepo-python pull request #50
Opened 2023-05-30 14:49 UTC by avazquezrd

From #49. I have not yet tested this, but I think it could be a first approach. I have introduced a second callback definition in `session` module and, in `subscription`, I directly pass to the callback the session instance that is currently being created.

Note that in line 251 I specified `Any` instead of `SysrepoSession` class, as that attribute is being declared inside the class itself. Any other option or suggestion is welcome.

2023-05-30 15:00 UTC, rjarry requested changes
I think we'll need a completely different API to subscribe with a different callback that takes only the (session, event, req_id and private_data) as parameters. The changes can be retrieved by accessing the session object.

Maybe something like:

```python
class SysrepoSession:

    UnsafeModuleChangeCallbackType = Callable[["SysrepoSession", str, int, Any], None]

    def subscribe_module_change_unsafe(
        self,
        module: str,
        xpath: Optional[str],
        callback: UnsafeModuleChangeCallbackType,
        *,
        priority: int = 0,
        passive: bool = False,
        done_only: bool = False,
        enabled: bool = False,
        private_data: Any = None,
    ) -> None:
```

It should be made EXPLICIT that the callback should NEVER keep a reference on the implicit session object to avoid use-after-free bugs. Probably the unsafe word is a bit extreme but I'd prefer if users are careful when using this API.

What do you think?

2023-05-31 09:16 UTC, avazquezrd commented
I have the new API as proposed and a new test for _unsafe_ subscription. I have added the optional _unsafe_ flag to `Subscription` class, so the same `module_change_callback` method can be used (if the flag is enabled, it returns the implicit session without retrieving changes or extra info).

Could you check it? Thanks!

2023-05-31 09:16 UTC, rjarry requested changes
Hey Adrian,

This is starting to look good :)

Could you update `examples/application.py` to use that new `subscribe_module_change_unsafe` API?

Thanks for your work.

2023-05-31 09:16 UTC, rjarry commented on sysrepo/session.py
> +        callback: ModuleChangeCallbackType,
This should be `UnsafeModuleChangeCallbackType`

2023-05-31 09:16 UTC, rjarry commented on sysrepo/session.py
> +        private_data: Any = None,
Maybe we could still add the `asyncio_register` argument (default to `False`).

2023-05-31 09:16 UTC, rjarry commented on sysrepo/session.py
> +        _check_subscription_callback(callback, self.UnsafeModuleChangeCallbackType)
You need to ensure that the callback is not async here and return an explicit error if it is.

2023-05-31 09:21 UTC, avazquezrd commented on sysrepo/session.py
> +        private_data: Any = None,
Would it be useful? As you said, async callbacks should not work with this unsafe callback.

2023-05-31 09:41 UTC, rjarry commented on examples/application.py
> +                )
Do you think it is worth it to subscribe twice? I was thinking of replacing the existing callback.

2023-05-31 09:44 UTC, avazquezrd commented on examples/application.py
> +                )
Well, as it is an example script I think it is good to show the user the different options exposed by the API.

2023-05-31 09:45 UTC, rjarry requested changes
A few more changes please :)

Can you squash all commits and add more details in your commit message? Don't hesitate to be verbose.

Thanks for adding unit tests by the way!

2023-05-31 09:45 UTC, rjarry commented on sysrepo/session.py
> +            unsafe=True,
You forgot to pass `asyncio_register` to the `Subscription` object here.

2023-05-31 09:45 UTC, rjarry commented on sysrepo/session.py
> +    reference on the implicit session object to avoid use-after-free bugs.
This warning should be in ALL CAPS :)

2023-05-31 09:45 UTC, rjarry commented on sysrepo/session.py
> +        Subscribe for changes made in the specified module.
Can you extend this description to explain the differences between this function and `subscribe_module_change`?

2023-05-31 10:39 UTC, avazquezrd commented on examples/application.py
> +                    module_change_cb,
Fixed, tested and working fine.

2023-05-31 12:14 UTC, rjarry approved these changes

2023-05-31 12:14 UTC, merged

2023-05-31 13:23 UTC, avazquezrd commented
Could it be possible to tag latest master and make it available in pypi? Thanks!

2023-05-31 14:28 UTC, rjarry commented
Done: https://pypi.org/project/sysrepo/1.5.0/