add sr_get_module_ds_access API
sysrepo/sysrepo-python pull request #61
Opened 2024-03-04 08:10 UTC by tbsuht

In order to read teh owner, group and permissions of a module, this PR adds binding for the `sr_get_module_ds_access` C function.

I'm not an expert with cffi, so let me know if there are things to improve :)
Do you think returning a tuple from the function is fine or would you expect a dedicated type?

Thanks in advance!

2024-03-04 08:16 UTC, tbsuht commented
I'm not sure about the failing CI tests: is this related to my changes? Seems unrelated, but I'm not sure.

2024-03-07 07:53 UTC, tbsuht commented
@rjarry I guess this is because `libyang-python` is running against the devel branch of `libyang`, which is already preparing for version 3.x?

2024-03-26 11:03 UTC, rjarry requested changes

2024-03-26 11:03 UTC, rjarry commented on sysrepo/connection.py
> +    ) -> tuple[str, str, int]:
`tuple[...]` is only supported since python 3.9. https://peps.python.org/pep-0585/

Could you replace this with `typing.Tuple`?

2024-03-28 08:54 UTC, tbsuht commented on sysrepo/connection.py
> +            The owner, group and permissions of the given module name.
These are names. I've updated the docs

2024-03-28 08:57 UTC, tbsuht commented on tests/test_connection.py
> +            self.assertTrue(len(group) > 0)
Any idea how to do the user check in the test on CI? Locally the check is working fine.

```Traceback (most recent call last):
  File "/home/runner/work/sysrepo-python/sysrepo-python/tests/test_connection.py", line 87, in test_conn_get_module_infos
    self.assertEqual(group, getpass.getuser())
AssertionError: 'docker' != 'runner'
- docker
+ runner
```

2024-03-28 09:59 UTC, rjarry requested changes

2024-03-28 09:59 UTC, rjarry commented on cffi/cdefs.h
> +int sr_get_module_ds_access(sr_conn_ctx_t *conn, const char *module_name, int mod_ds, char **owner, char **group, mode_t *perm);
Nitpick: this file is missing a final new line character `\n`

2024-03-28 09:59 UTC, rjarry commented on README.rst
>  --------------------------
Nitpick: can you make the title underline the same length than the text?

2024-03-28 10:10 UTC, rjarry commented on tests/test_connection.py
> +            self.assertTrue(len(group) > 0)
That's weird. Maybe `docker` and `runner` are aliases of the same UID.

Maybe you can change the check with something like the following:

```python
import pwd, os, grp

self.assertEqual(pwd.getpwnam(owner).pw_uid, os.geteuid())
self.assertEqual(grp.getgrnam(group).gr_gid, os.getegid())
```

This may be completely overkill though :D Your original check was probably enough...

2024-03-28 10:17 UTC, tbsuht commented on tests/test_connection.py
> +            self.assertTrue(len(group) > 0)
Great, works! Thanks! :)

2024-03-28 10:19 UTC, tbsuht commented
Can you create a new tag once merged or what's the policy?

2024-03-28 10:37 UTC, rjarry requested changes
Thanks for the changes. One last thing, could you update your commit message following the rules I am putting in place?

https://github.com/sysrepo/sysrepo-python/pull/64

In a nutshell, your commit message should look like this:

```
connection: add sr_get_module_ds_access API

Add a new function to get owner, group and permissions of a module based
on its name.

Signed-off-by: Bagg Tobias (ETAS-DAP/XPC-Fe3) <Tobias.Bagg@etas.com>
```

Thanks!

2024-03-28 10:37 UTC, rjarry commented
> Can you create a new tag once merged or what's the policy?

Yes, I can make a release if you want.

2024-03-28 10:42 UTC, tbsuht commented
> Thanks for the changes. One last thing, could you update your commit message following the rules I am putting in place?
> 
> #64
> 
> In a nutshell, your commit message should look like this:
> 
> ```
> connection: add sr_get_module_ds_access API
> 
> Add a new function to get owner, group and permissions of a module based
> on its name.
> 
> Signed-off-by: Bagg Tobias (ETAS-DAP/XPC-Fe3) <Tobias.Bagg@etas.com>
> ```
> 
> Thanks!

Done

2024-03-28 10:48 UTC, merged

2024-03-28 10:48 UTC, rjarry commented
Thanks!

2024-03-28 10:56 UTC, rjarry commented
pypi.org uploads are suspended temporarily.

https://github.com/sysrepo/sysrepo-python/actions/runs/8466165185/job/23194386178#step:9:32

I'll re-run the failed deploy job later.